// Code generated by MockGen. DO NOT EDIT.
// Source: dfpath.go
//
// Generated by this command:
//
//	mockgen -destination mocks/dfpath_mock.go -source dfpath.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDfpath is a mock of Dfpath interface.
type MockDfpath struct {
	ctrl     *gomock.Controller
	recorder *MockDfpathMockRecorder
	isgomock struct{}
}

// MockDfpathMockRecorder is the mock recorder for MockDfpath.
type MockDfpathMockRecorder struct {
	mock *MockDfpath
}

// NewMockDfpath creates a new mock instance.
func NewMockDfpath(ctrl *gomock.Controller) *MockDfpath {
	mock := &MockDfpath{ctrl: ctrl}
	mock.recorder = &MockDfpathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDfpath) EXPECT() *MockDfpathMockRecorder {
	return m.recorder
}

// LogDir mocks base method.
func (m *MockDfpath) LogDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// LogDir indicates an expected call of LogDir.
func (mr *MockDfpathMockRecorder) LogDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDir", reflect.TypeOf((*MockDfpath)(nil).LogDir))
}

// PluginDir mocks base method.
func (m *MockDfpath) PluginDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PluginDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// PluginDir indicates an expected call of PluginDir.
func (mr *MockDfpathMockRecorder) PluginDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PluginDir", reflect.TypeOf((*MockDfpath)(nil).PluginDir))
}
