version: "2"
run:
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - gci
    - gofmt

linters-settings:
  gocyclo:
    min-complexity: 100
  gci:
    sections:
      - standard
      - default
      - prefix(d7y.io/api)
      - prefix(d7y.io/dragonfly/v2)

issues:
  new: true
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1019:'
  exclude-dirs:
    - third_party
    - builtin
    - examples

output:
  formats:
    - format: tab
      path: stdout
  print-linter-name: true
  print-issued-lines: true