package com.alibaba.dragonfly.supernode.service.cdn;

import static org.mockito.AdditionalMatchers.or;
import static org.mockito.Matchers.isA;
import static org.mockito.Matchers.isNull;
import static org.powermock.api.mockito.PowerMockito.mockStatic;

import com.alibaba.dragonfly.supernode.service.cdn.LinkPositiveGc;
import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@PowerMockIgnore({"javax.management.*"})
@RunWith(PowerMockRunner.class)
public class LinkPositiveGcTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: LinkPositiveGc */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 33 branch to line 33
   *  - conditional line 33 branch to line 34
   */

  @Test
  public void gcInputNotNullOutputTrue() {

    // Arrange
    final LinkPositiveGc objectUnderTest = new LinkPositiveGc();
    final String taskId = "!";

    // Act
    final boolean retval = objectUnderTest.gc(taskId);

    // Assert result
    Assert.assertEquals(true, retval);
  }
}
