package mgr

import (
	"context"

	"github.com/dragonflyoss/Dragonfly/apis/types"
)

// DfgetTaskMgr as an interface defines all operations against DfgetTask.
// A DfgetTask represents a download process initiated by dfget or other clients.
type DfgetTaskMgr interface {
	// Add a new dfgetTask, we use clientID to identify a dfgetTask uniquely.
	// ClientID should be generated by dfget, supernode will use it directly.
	// NOTE: We should create a new dfgetTask for each download process,
	//       even if the downloads initiated by the same machine.
	Add(ctx context.Context, dfgetTask *types.DfGetTask) error

	// Get get a dfgetTask info with specified clientID.
	Get(ctx context.Context, clientID string) (dfgetTask *types.DfGetTask, err error)

	// List return the list of dfgetTask.
	List(ctx context.Context, filter map[string]string) (dfgetTaskList []*types.DfGetTask, err error)

	// Delete a dfgetTask with clientID.
	Delete(ctx context.Context, clientID string) error

	// UpdateStatus update the status of dfgetTask with specified clientID.
	// Supernode will update the status of dfgetTask in the following situations:
	// 1. after init the dfgetTask
	// 2. when success/fail to download some pieces
	// 3. when the entire download process ends in success or failure
	UpdateStatus(ctx context.Context, clientID string, status string) error
}
