// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// CdnSource cdn source
// swagger:model CdnSource
type CdnSource string

const (

	// CdnSourceSupernode captures enum value "supernode"
	CdnSourceSupernode CdnSource = "supernode"

	// CdnSourceSource captures enum value "source"
	CdnSourceSource CdnSource = "source"
)

// for schema
var cdnSourceEnum []interface{}

func init() {
	var res []CdnSource
	if err := json.Unmarshal([]byte(`["supernode","source"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cdnSourceEnum = append(cdnSourceEnum, v)
	}
}

func (m CdnSource) validateCdnSourceEnum(path, location string, value CdnSource) error {
	if err := validate.Enum(path, location, value, cdnSourceEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this cdn source
func (m CdnSource) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCdnSourceEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
