// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PieceUpdateRequest piece update request
// swagger:model PieceUpdateRequest
type PieceUpdateRequest struct {

	// ID
	ID string `json:"ID,omitempty"`
}

// Validate validates this piece update request
func (m *PieceUpdateRequest) Validate(formats strfmt.Registry) (err error) {
	return err
}

// MarshalBinary interface implementation
func (m *PieceUpdateRequest) MarshalBinary() (b []byte, err error) {
	if m == nil {
		return
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PieceUpdateRequest) UnmarshalBinary(b []byte) (err error) {
	var res PieceUpdateRequest
	if err = swag.ReadJSON(b, &res); err != nil {
		return
	}
	*m = res
	return
}
