// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PreheatInfo return detailed information of a preheat task in supernode
//
// swagger:model PreheatInfo
type PreheatInfo struct {

	// ID of preheat task.
	//
	ID string `json:"ID,omitempty"`
}

// Validate validates this preheat info
func (m *PreheatInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PreheatInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PreheatInfo) UnmarshalBinary(b []byte) error {
	var res PreheatInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
