// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskFetchInfo It shows the task info and pieces info.
// swagger:model TaskFetchInfo
type TaskFetchInfo struct {

	// The pieces which should belong to the peer node
	Pieces []*PieceInfo `json:"pieces"`

	// task
	Task *TaskInfo `json:"task,omitempty"`
}

// Validate validates this task fetch info
func (m *TaskFetchInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePieces(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTask(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskFetchInfo) validatePieces(formats strfmt.Registry) error {

	if swag.IsZero(m.Pieces) { // not required
		return nil
	}

	for i := 0; i < len(m.Pieces); i++ {
		if swag.IsZero(m.Pieces[i]) { // not required
			continue
		}

		if m.Pieces[i] != nil {
			if err := m.Pieces[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pieces" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TaskFetchInfo) validateTask(formats strfmt.Registry) error {

	if swag.IsZero(m.Task) { // not required
		return nil
	}

	if m.Task != nil {
		if err := m.Task.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("task")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskFetchInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskFetchInfo) UnmarshalBinary(b []byte) error {
	var res TaskFetchInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
