// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TaskInfo detailed information about task in supernode.
// swagger:model TaskInfo
type TaskInfo struct {

	// ID of the task.
	ID string `json:"ID,omitempty"`
}

// Validate validates this task info
func (m *TaskInfo) Validate(formats strfmt.Registry) (err error) {
	return err
}

// MarshalBinary interface implementation
func (m *TaskInfo) MarshalBinary() (b []byte, err error) {
	if m == nil {
		return
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskInfo) UnmarshalBinary(b []byte) (err error) {
	var res TaskInfo
	if err = swag.ReadJSON(b, &res); err != nil {
		return
	}
	*m = res
	return
}
