// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TaskCreateResponse response get from task creation request.
// swagger:model TaskCreateResponse
type TaskCreateResponse struct {

	// ID of the created task.
	ID string `json:"ID,omitempty"`
}

// Validate validates this task create response
func (m *TaskCreateResponse) Validate(formats strfmt.Registry) (err error) {
	return err
}

// MarshalBinary interface implementation
func (m *TaskCreateResponse) MarshalBinary() (b []byte, err error) {
	if m == nil {
		return
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskCreateResponse) UnmarshalBinary(b []byte) (err error) {
	var res TaskCreateResponse
	if err = swag.ReadJSON(b, &res); err != nil {
		return
	}
	*m = res
	return
}
