// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TaskUpdateRequest request used to update task attributes.
// swagger:model TaskUpdateRequest
type TaskUpdateRequest struct {

	// ID of the peer which has finished to download the whole task.
	PeerID string `json:"peerID,omitempty"`
}

// Validate validates this task update request
func (m *TaskUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskUpdateRequest) UnmarshalBinary(b []byte) error {
	var res TaskUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
