name: 'Auto Assign'

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@f27c8acd2431d855340e469af809c2452e58b7b8
